slackhq/vitess

.github/workflows/slackhq_upstream_sync.yml
This PR adds automation for syncing the following branches from  [vitessio/vitess](https://github.com/vitessio/vitess):
- `main`
- `release-12.0`
- `release-13.0`
- `release-14.0`
This GitHub Action will run once daily or when triggered manually at https://github.com/slackhq/vitess/actions. Luckily, this file does not get paved-over by itself
-   [ ] "Backport me!" label has been added if this change should be backported
=> Add repo sync GitHub Action

.github/workflows/slackhq_upstream_sync.yml
This PR stops auto-syncing `release-*` branches (for now) because they are failing and cause `main` to fail as well
I'll add release branch syncing at a later date
=> Stop syncing release-* branches

go/vt/vtgate/vstream_manager.go
backport vstream OOM fix: PR https://github.com/vitessio/vitess/pull/10571 (https://github.com/tinyspeck/vitess/pull/252)
-   [ ] "Backport me!" label has been added if this change should be backported
=> backport upstream PR 10571

go/mysql/auth_server_clientcert_test.go, go/mysql/client_test.go, go/mysql/conn.go, go/mysql/fakesqldb/server.go, go/mysql/handshake_test.go, go/mysql/query_benchmark_test.go, go/mysql/server.go, go/mysql/server_test.go, go/vt/vtgate/plugin_mysql_server.go
As the title suggests, this is a backport of a change that was made in [upstream change](https://github.com/vitessio/vitess/pull/11167)  for the v15 release.
Most all changes there were applied to our v12 branch except for:
- changes to the endtoend flags tests(they don't exist in v12)
- changes to the v15 changelog(obviously doesn't exist in v12)
- new benchmark tests added
- some unit tests pass(most end up being marked as flaky in future release)
- deployed this to dev and started up as expected with the new flag off and on
=> [vtgate] Backport vitessio/vitess#11167

go/cmd/vtctldclient/command/backups.go, go/vt/mysqlctl/azblobbackupstorage/azblob.go, go/vt/mysqlctl/backup.go, go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/backupstorage/interface.go, go/vt/mysqlctl/builtinbackupengine.go, go/vt/mysqlctl/cephbackupstorage/ceph.go, go/vt/mysqlctl/filebackupstorage/file.go, go/vt/mysqlctl/gcsbackupstorage/gcs.go, go/vt/mysqlctl/s3backupstorage/s3.go, go/vt/mysqlctl/xtrabackupengine.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/wrangler/traffic_switcher.go
These are cherrypicks needed in vtctld for vtadmin UI to work, similarly as what we did in v11 upgrade through PR 
https://github.com/tinyspeck/vitess/pull/247.
However, the majority changes in https://github.com/tinyspeck/vitess/pull/247 are already in v12, so in this PR, just backport those are not in v12.
The branch `slack-vitess-r12.0.5-vtctld` is based on the v12 release branch `slack-vitess-r12.0.5`, and `slack-vitess-r12.0.5-vtctld` will be used for deployment.
For reference:
```
This will serve as the base branch for 11.x vtctld branches, and should not be merged into master.
I compiled a list of cherry picks you see below from the following PRs:
https://github.com/tinyspeck/vitess/pull/231
https://github.com/tinyspeck/vitess/pull/232
https://github.com/tinyspeck/vitess/pull/233 …
```
=> Slack vitess r12.0.5 vtctld cherrypicks

go/mysql/collations/integration/coercion_test.go
The CI test `Unit Test (mysql80) / test (pull_request)` failed with this error:
```
--- FAIL: TestComparisonSemantics (13.17s)
--- FAIL: TestComparisonSemantics/equals (6.40s)
coercion_test.go:202: expected dec8_swedish_ci vs utf8_general_ci to fail coercion: Illegal mix of collations (dec8_swedish_ci,EXPLICIT) and (utf8mb3_general_ci,EXPLICIT) for operation '=' (errno 1267) (sqlstate HY000) during query: SELECT CAST(((_dec8 X'6162636441424344[30](https://github.com/slackhq/vitess/actions/runs/3414744449/jobs/5683094619#step:8:31)31323334' COLLATE "dec8_swedish_ci") = (_utf8 X'61626364414243443031323334' COLLATE "utf8_general_ci")) AS BINARY), COLLATION((_dec8 X'61626364414243443031323334' COLLATE "dec8_swedish_ci") = (_utf8 X'61626364414243443031323334' COLLATE "utf8_general_ci")), …
```
=> backport - fix collation failure

go/vt/vtgate/discoverygateway.go, go/vt/vtgate/gateway.go, go/vt/vtgate/tabletgateway.go
Copying over the patch to route REPLICA queries to RDONLY tablets from discoverygateway to the tabletgateway.
previous patch to the discoverygateway: https://github.com/slackhq/vitess/commit/47adb7c8fc720cb4cb7a090530b3e88d310ff6d3
=> port discoverygateway rdonly patch to tabletgateway

go/vt/vtgate/gateway.go, go/vt/vtgate/tabletgateway.go
Applying the RDONLY patch to the tabletgateway that routes REPLICA queries to these tablets to our v13 branch 
https://github.com/slackhq/vitess/pull/17
=> add rdonly patch to tabletgateway for v13

go/sqltypes/result.go, go/sqltypes/result_test.go
similarly as [what we did for v12 ](https://github.com/slackhq/vitess/pull/1), we need to patch the upstream PR 4660 (Fix panic in vtgate when MakeRowTrusted gets bad result).. We still consider to work with upstream on a real fix in the near future.
context: https://github.com/vitessio/vitess/pull/4660
=> patch upstream pr 4660 (Fix panic in vtgate when MakeRowTrusted gets bad result)

go/vt/vtgate/tabletgateway.go
Fixes a nuance with the `tabletgateway` code and our RDONLY patch where if the tablet selected is a RDONLY, tabletgateway passes in the original target request as REPLICA instead of RDONLY. 
This PR updates the target to whatever the selected tablet's target is similar to what `discoverygatweay` does.
More context: https://slack-pde.slack.com/archives/C01CVUUUREF/p1670437058252249
=> update tabletgateway to pass in target of selected tablet for rdonly patch

docker/base/Dockerfile, docker/base/Dockerfile.mariadb, docker/base/Dockerfile.mariadb103, docker/base/Dockerfile.mysql56, docker/base/Dockerfile.mysql80, docker/base/Dockerfile.percona, docker/base/Dockerfile.percona57, docker/base/Dockerfile.percona80
This PR allows `BUILD_GIT_BRANCH` and `BUILD_GIT_REV` to be passed-into docker-based builds _(via `Dockerfile`s in [`docker/base`](https://github.com/vitessio/vitess/tree/main/docker/base))_ of Vitess, so that the `BuildGitBranch` and `BuildGitRev` stats return correct information
I plan to submit this to the upstream project after successful testing
Currently we are passing these 2 x env vars to our builds like so:
```bash
docker build \
--build-arg BUILD_GIT_REV="$(git rev-parse --short HEAD)" \
--build-arg BUILD_GIT_BRANCH="$GIT_BRANCH" \
--build-arg BUILD_NUMBER="$BUILD_NUMBER" \
-t "${IMAGE_TAG}" \
-f "${WORKDIR}/docker/base/Dockerfile.${FLAVOR}" "${WORKDIR}"
```
However `docker build` returns this warning that indicates they were ignored:
```bash
[Warning] One or more build-args …
```
=> Allow BUILD_GIT_BRANCH and BUILD_GIT_REV override in docker build

go/vt/vttablet/tabletmanager/rpc_replication.go
In V13, on replicas, the vttablet process restart failed with the error:
```
F1213 16:50:17.939918   22744 tm_init.go:741] RestoreFromBackup failed: The MySQL server is running with the --super-read-only opt
ion so it cannot execute this statement (errno 1290) (sqlstate HY000) during query: CREATE DATABASE IF NOT EXISTS _vt
```
which hits the problems described in the upstream PR https://github.com/vitessio/vitess/pull/10448
details in thread https://slack-pde.slack.com/archives/CQGR39RA5/p1670979804634929
=> Change super_read_only default back to false

go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
This PR updates the new `VStreamerCount` stat to match the approach PlanetScale suggested in the upstream PR https://github.com/vitessio/vitess/pull/11978 (merged)
Currently our fork implements the same new stat but it uses a mutex. The PR accepted by upstream does not use a mutex, which is smarter
=> Use stats.Gauge w/o mutex for VStreamerCount stat

go/vt/vitessdriver/rows.go, go/vt/vitessdriver/rows_test.go
This is a backport of this PR. See this link for the context. https://github.com/vitessio/vitess/pull/12007
=> Implement the RowsColumnTypeScanType interface in the go sql driver for Vitess in order to get the column types

.github/workflows/upgrade_downgrade_test_backups_e2e.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_query_serving.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml, go/mysql/collations/integration/coercion_test.go
Signed-off-by: 'Priya Bibra' <pbibra@slack-corp.com>
Some of the tests against the v13 branch are failing due to a bump in the upgrade tests from v14.0.2 to v14.0.4
The latter requires a higher go version and since this tag is fixed, I'm bumping the version manually.
Discussion here: https://slack-pde.slack.com/archives/C021CPS1BNF/p1675708897542689?thread_ts=1674777609.913009&cid=C021CPS1BNF
Bumping mysql version from `8.0.31` to `8.0.32` for coercion semantics test as well.
=> update go version for test workflows

.github/workflows/cluster_endtoend_vtgate_tablet_healthcheck_cache.yml, go/test/endtoend/cluster/vttablet_process.go, go/test/endtoend/tabletgateway/vtgate_test.go, go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go, go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go, go/vt/discovery/tablet_health_check.go, go/vt/discovery/topology_watcher_test.go, go/vt/vtgate/executor.go, test/config.json
Signed-off-by: Priya Bibra <pbibra@slack-corp.com>
This PR backports two upstream patches to resolve some vtgate health cache issues.
1. When tablets were removed from the topo, vtgate's secondary cache was not properly being cleared. This is fixed in upstream patch 9106: https://github.com/vitessio/vitess/pull/9106
2. When tablets' type changes from their original creation type, and then they are removed from the topo, vtgate's secondary cache was not properly being cleared. This is fixed in patch 12178: https://github.com/vitessio/vitess/pull/12178
Both problems affected the vtgate's `/debug/status` page and the `show vitess_tablets` queries. VTAdmin also periodically fails to load schemas because it relies on these commands to get up to date tablet information.
**Testing**
``` …
```
=> backport upstream patch 12178 and 9106

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go
backport patch to delete tablets from secondary cache when state changes and they are deprovisioned: https://github.com/vitessio/vitess/pull/12178
=> apply patch 12178

go/vt/vttablet/tabletserver/state_manager.go, go/vt/vttablet/tabletserver/state_manager_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tabletserver_test.go
This PR backports the following 2 x PRs (from v13+) that should cause tablets with crashed `mysqld`s to become `NOT_SERVING`
PRs:
1. https://github.com/vitessio/vitess/pull/11524
2. https://github.com/vitessio/vitess/pull/11895
- Depends on 1st PR
=> Backport v13+ `CheckMySQL` fixes in tabletserver state manager

docker/base/Dockerfile, docker/base/Dockerfile.mariadb, docker/base/Dockerfile.mariadb103, docker/base/Dockerfile.mysql80, docker/base/Dockerfile.percona57, docker/base/Dockerfile.percona80
Backport of upstream PR: https://github.com/vitessio/vitess/pull/11968
https://github.com/vitessio/vitess/pull/11968
=> Backport: Allow override of build git env in docker/base builds (#11968)

go/flags/endtoend/vtgate.txt, go/mysql/auth_server_clientcert_test.go, go/mysql/client_test.go, go/mysql/conn.go, go/mysql/fakesqldb/server.go, go/mysql/handshake_test.go, go/mysql/query_benchmark_test.go, go/mysql/server.go, go/mysql/server_flaky_test.go, go/vt/vtgate/plugin_mysql_server.go
as PR #27, need to backport to v14 as well. 
=> `slack-vitess-r14.0.5` Backport vitessio/vitess#11167-vtgate buffer fix

go/mysql/sql_error.go, go/mysql/sql_error_test.go
Upstream PR: https://github.com/vitessio/vitess/pull/12949
> This error code seems better suited to represent the fact that transactions are being throttled by the server due to some form of resource contention than the current code 1203 ER_TOO_MANY_USER_CONNECTIONS.
=> `slack-vitess-r14.0.5-dsdefense`: backport vitessio/vitess#12949

go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
Upstream backport of PR: https://github.com/vitessio/vitess/pull/12901
https://github.com/vitessio/vitess/pull/12901
=> `slack-vitess-r14.0.5-dsdefense`: backport `txthrottler` cleanup PR vitessio/vitess#12901

go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go
Upstream backport of https://github.com/vitessio/vitess/pull/13098
https://github.com/vitessio/vitess/issues/13099
-   [X] "Backport to:" labels have been added if this change should be back-ported
-   [X] Tests were added or are not required
-   [X] Did the new or modified tests pass consistently locally and on the CI
-   [X] Documentation was added or is not required
=> Add vstream metrics to vtgate (#13098)

go/vt/vtgate/plugin_mysql_server.go
Change parameter to use underscore like others
=> Use underscores like other parameters

go/vt/vtgate/plugin_mysql_server.go
fix connection buffer parameter to use underscore
=> fix parameter name

go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
Backport https://github.com/vitessio/vitess/pull/12902. Some (but not all) of this PR was already backported by a previous upstream PR that was "ahead" of this one - I'm guessing some of the changes were missed in cherry-pick conflict resolution
https://github.com/vitessio/vitess/pull/12902
=> `slack-vitess-r14.0.5-dsdefense`: txthrottler: further code cleanup (#12902)

config/tablet/default.yaml, doc/ReplicationLagBasedThrottlingOfTransactions.md, go/flags/endtoend/vttablet.txt, go/vt/mysqlctl/rice-box.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletenv/config_test.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
This backports the upstream PR https://github.com/vitessio/vitess/pull/12174
A few tweaks needed to be made in this backport because `topoproto.TabletTypeListFlag` doesn't exist in v14, because flag parsing hadn't totally moved to `github.com/spf13/pflag`. Specifically, tweaks had to be made to set the flag default in `.Init()`, which caused some unit tests to fail until they were tweaked as well. Also a "rice box" had to be updated - something that no longer exists on upstream `main`
https://github.com/vitessio/vitess/pull/12174
=> `slack-vitess-r14.0.5-dsdefense`: Add flag to select tx throttler tablet type (vitessio#12174)

go/vt/vtgate/plugin_mysql_server.go
Reverts slackhq/vitess#93
It turned out upstream is doing this format anyway. The old format is in fact the new format.
=> Revert "fix parameter name"

go/vt/vtgate/plugin_mysql_server.go
Reverts slackhq/vitess#94
It turned out upstream is doing this format anyway. The old format is in fact the new format.
=> Revert "fix param using underscore"

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go
Apply [this](https://github.com/slackhq/vitess/pull/48/files) patch to our v14 branch to fix: https://slack-pde.slack.com/archives/CQGR39RA5/p1688419131996039
=> apply patch 12178 to v14

go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
This is a backport of upstreamed https://github.com/vitessio/vitess/pull/13526
[DRE-8938](https://jira.tinyspeck.com/browse/DRE-8938)
N/A
=> DRE-8938 Add per workload TxThrottler metrics

go/vt/topo/consultopo/server.go
**NOTE: replaces PR https://github.com/slackhq/vitess/pull/107**
This PR allows overrides to `http.Transport` settings of the Consul topo client
This is to help address crashes we're seeing when too many consul connections are opened by vtctld
`vtctld --help`:
```
tvaillancourt@tvailla-ltmxctu vitess % ./vtctld --help 2>&1|grep -A1 topo_consul
-topo_consul_idle_conn_timeout duration
Maximum amount of time to pool idle connections. (default 1m30s)
-topo_consul_lock_delay duration
LockDelay for consul session. (default 15s)
-topo_consul_lock_session_checks string
List of checks for consul session. (default "serfHealth")
-topo_consul_lock_session_ttl string
TTL for consul session.
-topo_consul_max_conns_per_host int
Maximum number of consul connections per host.
-topo_consul_max_idle_conns …
```
=> `slack-vitess-r12.0.5`: allow conn overrides in consul topo

.github/workflows/cluster_endtoend_shardedrecovery_stress_verticalsplit_heavy.yml
This aims at solving new failure modes seen with the larger runners, such as 
```
panic: test timed out after 20m0s
```
seen, for example, [here](https://github.com/slackhq/vitess/actions/runs/5747772848/job/15581935154?pr=112).
https://jira.tinyspeck.com/browse/DRE-8938
=> Revert change of runner type for shardedrecovery_stress_verticalsplitheavy

go/flags/endtoend/vtgate.txt, go/flags/endtoend/vttablet.txt, go/vt/topo/consultopo/server.go
This PR is a copy of the v12 PR https://github.com/slackhq/vitess/pull/108
This adds flags to tune the connection usage of the consul topo
cc @vmogilev / @rvrangel / @ejortegau 
https://github.com/slackhq/vitess/pull/108
=> `slack-vitess-r14.0.5`: allow conn overrides in consul topo

go/flags/endtoend/vtgate.txt, go/vt/vtexplain/vtexplain_vtgate.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_stream_test.go, go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go, go/vt/vtgate/vtgate.go, go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go
We are planning on support vstream copy testing in dev. This flag ensures we don't accidentally allow this in production until RDONLYs are properly supported for bootstrapping. This is only temporary and will be removed from our fork once we're ready in all environments.
=> add vtgate flag that explicitly allows vstream copy

go/vt/vtgate/endtoend/main_test.go, go/vt/vtgate/endtoend/vstream_test.go, go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go, go/vt/vttablet/tabletserver/vstreamer/uvstreamer_flaky_test.go
Apply patch 1103: https://github.com/vitessio/vitess/pull/11103
Note: missing `doc/releasenotes/16_0_0_summary.md` and function `sqlparser.NewTableIdent()` is renamed in v15.
=> apply vcopy patch 11103

go/test/endtoend/vreplication/vstream_test.go, go/vt/vtgate/endtoend/main_test.go, go/vt/vtgate/endtoend/misc_test.go, go/vt/vtgate/endtoend/row_count_test.go, go/vt/vtgate/endtoend/vstream_test.go, go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go, go/vt/vttest/local_cluster.go
Patch 11909: https://github.com/vitessio/vitess/pull/11909
=> apply patch 11909

go/vt/discovery/tablet_picker.go, go/vt/discovery/tablet_picker_test.go, go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go
apply https://github.com/vitessio/vitess/pull/14224
This adds the ability to ignore certain tablets on retry if applicable, along with retrying GTIDSet Mismatch errors.
=> backport #14224

.github/workflows/update_golang_version.yml
I wonder if a computer can be better at upgrading Go than a human. I think this is how you are meant to upgrade Go version in Vitess anyway ¯\_(ツ)_/¯
It won't upgrade the major version on a release branch (only does it on the main), but I'm willing to experiment with this.
=> enable go-upgrade job for slack-vitess-r14.0.5

go/cmd/vtgateproxy/vtgateproxy.go, go/vt/vtgateproxy/discovery.go, go/vt/vtgateproxy/vtgateproxy.go
Add discovery from a json file in the format: 
```
./vtgateproxy --target "vtgate://aux?num_connections=5&az_id=use1-az1" --json_config vtgate_config.json
```
=> First draft of discovery

go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json
This PR backports the upstream PR https://github.com/vitessio/vitess/pull/14426 using [the `v16` backport](https://github.com/vitessio/vitess/pull/14428) of this change, as that is the closest release to `v14`
1. https://github.com/vitessio/vitess/pull/14426 _(original PR)_
2. https://github.com/vitessio/vitess/pull/14428 _(v16 backport)_
=> `slack-vitess-r14.0.5`: backport vitessio/vitess#14428 from v16

go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json
This PR backports the upstream PR https://github.com/vitessio/vitess/pull/14426 using [the `v16` backport](https://github.com/vitessio/vitess/pull/14428) of this change, as that is the closest release to `v15`
1. https://github.com/vitessio/vitess/pull/14426 _(original PR)_
2. https://github.com/vitessio/vitess/pull/14428 _(v16 backport)_
=> `slack-vitess-r15.0.5`: backport vitessio/vitess#14428 from v16

go/flags/endtoend/vtgate.txt, go/flags/endtoend/vttablet.txt, go/vt/vtgate/planbuilder/abstract/queryprojection.go, go/vt/vtgate/planbuilder/horizon_planning.go, go/vt/vtgate/planbuilder/testdata/aggr_cases.json, go/vt/vtgate/planbuilder/testdata/select_cases.json
This PR backports the upstream PR https://github.com/vitessio/vitess/pull/14426 to `slack-vitess-r14.0.5-dsdefense` using [an earlier backport to `slack-vitess-r14.0.5`](https://github.com/slackhq/vitess/pull/165)
1. https://github.com/vitessio/vitess/pull/14426 _(original PR)_
2. https://github.com/vitessio/vitess/pull/14428 _(v16 backport)_
3. https://github.com/slackhq/vitess/pull/165 _(Slack v14 backport)_
=> `slack-vitess-r14.0.5-dsdefense`: backport vitessio/vitess#14428 from v16 (#165)

go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go
Currently, vstreams fail as expected when trying to stream from a tablet that is being replaced for _some_ reason. However, when the `NOT_FOUND` error is returned to the vstream client it does not omit the restore tablet from being used during the next retry. This can lead to streams being blocked for multiple hours. 
The reason this is added to our fork instead of committed upstream is because this has been fixed in future versions of Vitess, but, when bringing that fix in, there were many dependencies that caused issues with the merge. This change will be added in order to unblock CDC until we are more caught up with upstream.
This change has been in dev over the last several weeks and recently it was [noted](https://slack-pde.slack.com/archives/C01P84R7L02/p1702586748407959) that the …
=> VStreams  NOT_FOUND Error Retries and Omits Tablet

go.mod, go.sum
DRE-9123: upgrades filepath-securejoin to v0.2.4
https://jira.tinyspeck.com/browse/DRE-9123
=> upgrades filepath-securejoin to v0.2.4

go/vt/grpcclient/client_auth_static.go, go/vt/grpcclient/client_auth_static_test.go, go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go
This PR backports https://github.com/vitessio/vitess/pull/15030 to our v14 branch
This is currently unmerged [but got a LGTM 👍 from upstream](https://github.com/vitessio/vitess/pull/15030#pullrequestreview-1870627261). If there are further changes I will sync them down
https://github.com/vitessio/vitess/pull/15030
=> `slack-vitess-r14.0.5`: load `--grpc_auth_static_client_creds` file once

docker/base/Dockerfile, docker/base/Dockerfile.mariadb, docker/base/Dockerfile.mariadb103, docker/base/Dockerfile.mysql80, docker/base/Dockerfile.percona57, docker/base/Dockerfile.percona80
This PR backports v16 PR https://github.com/vitessio/vitess/pull/11968 that fixes build-related metrics/vars so the git branch, commit, etc is displayed correctly
We currently rely on this backport in v12 + v14. The debt is payed down in v16
https://github.com/vitessio/vitess/pull/11968
=> `slack-vitess-r15.0.5`: backport upstream PR #11968

go/vt/vtgateproxy/vtgateproxy.go, misc/git/pre-commit
* Fix missing `Unlock` if an error happens when creating a connection
* Only register global dial options once
* Don't try to create a connection if one was made while waiting for write lock.
=> Fix locking in getConnection

go/cmd/vtgateproxy/vtgateproxy.go
This is enough to make prom metrics appear on `localhost:<--port>/metrics` with a `vtgateproxy` prefix so they can be scraped.
=> Enable prometheus stats on /metrics

go/cmd/vtgateproxy/vtgateproxy.go, go/vt/servenv/grpc_server.go
`--grpc_prometheus` enables server and client gRPC metrics. But if we don't have a gRPC server, but call `servenv.Run()` like we're doing here, the process will crash because of some uninitialized server state. Fix by moving the prom enable logic after the check to see if we actually have a server.
This is still a bug upstream, so I'll send the fix there as well.
=> Don't crash when gRPC metrics are enabled without a server

go/cmd/vtgateproxy/vtgateproxy.go, go/vt/vtgateproxy/discovery.go, go/vt/vtgateproxy/vtgateproxy.go
Refactor the discovery logic to have a single watcher for the parsed file, and then each resolver just gets callbacks from there as things change.
Clean up and consolidate the command line flags, and change a bit. The new set of options to run (tested in dev) are:
```
vtgateproxy \
--logtostderr=1 \
--port 15000 \ 
--mysql_server_port 15306 \
--mysql_auth_server_impl none \
--grpc_auth_static_client_creds /etc/slack.d/vt_grpc_static_auth_client_creds.json \ 
--vtgate_hosts_file /etc/vthosts/config_vtgate_hosts_rotor.json
--num_connections=4 \
--address_field nebula_address \
--port_field grpc \
--pool_type_field type \
--affinity_field az_id 
```
Implement a more efficient single pass shuffle scan because it seemed nifty.
Add some basic metrics for the discovery part:
``` …
```
=> Vtgateproxy rework discovery and add metrics

go/flags/endtoend/vtgate.txt, go/vt/vtgate/tabletgateway.go
This PR cherry-picks https://github.com/slackhq/vitess/pull/77 to the v15 branch 😢 
https://github.com/slackhq/vitess/pull/77
=> `slack-vitess-r15.0.5:`cherrypick rdonly patch (#77)

go/vt/vtgateproxy/discovery.go
Fix an issue with discovery where we're appending to the list of targets but never reinitialising it. Dead hosts are never removed from the list and active ones are added multiple times.
~Change metric types of active hosts from counters to gauges, we should only be tracking the current number not incrementing.~
I have tested this out with a local build and discovery is working correctly when the host list changes
=> reinitalise targets when parsing host list

go/vt/vtgateproxy/discovery.go, go/vt/vtgateproxy/vtgateproxy.go
- move organization of target hosts to parse time so we do it less often
- pass affinityValue in at run time instead of in the connection attributes
- rework discovery metrics
- add discovery data to the `/debug/status` endpoint
=> restructure discovery to do more up front

go/vt/vtgateproxy/discovery.go
@rjlaine found an issue where if the list of hosts changes e.g. from a scale up the new hosts may not end up in the list of target hosts. We can fix this by doing a shuffle sort during the parse phase.
=> shuffle targets during parse phase

.github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml, go.mod, go/flags/endtoend/vtbackup.txt, go/flags/endtoend/vtctld.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vtgr.txt, go/flags/endtoend/vtorc.txt, go/flags/endtoend/vttablet.txt, go/flags/endtoend/vttestserver.txt, go/internal/flag/flag.go, go/test/endtoend/reparent/plannedreparent/reparent_test.go, go/vt/servenv/exporter.go, go/vt/topo/consultopo/server.go, go/vt/vttest/topoctl.go, tools/unit_test_race.sh
This PR fixes a race introduced in PR https://github.com/slackhq/vitess/pull/297. This patch added [a `*api.Config`](https://pkg.go.dev/github.com/hashicorp/consul/api#Config) as a global var and it turns out this [contains an `*http.Transport`](https://pkg.go.dev/net/http#Transport) that will be held open due to global var scope - this can cause races in tests that leave idle connections open
Secondly, a race in `go/vt/servenv` is causing race CI problems. I partially pulled-in a flaky test fix from https://github.com/vitessio/vitess/pull/11520 _(see "Incidental flaky tests" in summary)_ to address this
This PR:
- Stops creating the `*api.Config` as a global var, instead the config is created every `.NewServer()` call
- Make `--topo_consul_max_conns_per_host` default to `250` now that …
=> `slack-vitess-r15.0.5`: fix races in `Unit Test (Race)` CI, fix "old" reparent CIs

go/vt/vtgateproxy/discovery.go
Minor improvement to the debug page to include the hostname for easier ... debugging.
=> vtgateproxy: include vtgate hostname in debug page

go/vt/vtgateproxy/firstready_balancer.go, go/vt/vtgateproxy/vtgateproxy.go
Implement a "first_ready" load balancer and a config to select it.
Despite how simple the code actually is, this balancer (I think!) does what (I think!) we want it to do (basically!):
* When the discovery returns N targets, the base code in the balancer will attempt to establish a SubConn to each of the targets, and will maintain that subconn with keepalives and retries.
* However when picking one of these for a given request, it always returns the first "ready" subconn.
This means that in practice, in steady state a webapp host will have one "hot" connection to a single vtgate, and will route all queries to it. At the same time it will maintain N-1 idle connections to other vtgates, and if the connection to the primary vtgate goes away or is interrupted, queries will get routed to one …
=> add firstready balancer

go/vt/vtgateproxy/firstready_balancer.go, go/vt/vtgateproxy/vtgateproxy.go
=> Vtgateproxy firstready balancer fail fast

go/vt/vtgate/grpcvtgateconn/conn.go
=> add vtgate_grpc_fail_fast option

go/vt/servenv/servenv.go, go/vt/vitessdriver/rows.go, go/vt/vitessdriver/rows_test.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtgate/vstream_manager.go, go/vt/vtgate/vstream_manager_test.go, go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
Backports:
1. https://github.com/vitessio/vitess/pull/11978
2. https://github.com/vitessio/vitess/pull/12007
3. https://github.com/vitessio/vitess/pull/12712
4. https://github.com/vitessio/vitess/pull/13098
Also [a fix for a flaky CI test](https://github.com/slackhq/vitess/pull/361/commits/d512ec2a7bcae709b82846b09e141ad92d411377) was added
=> `slack-vitess-r15.0.5`: misc required backports, pt. 1

docker/base/Dockerfile.mariadb, docker/base/Dockerfile.mariadb103, docker/base/Dockerfile.mysql80, docker/base/Dockerfile.percona57, docker/base/Dockerfile.percona80
This PR should fix access issues in our Jenkins build due to using a Durability Policy in a private repo, and the Docker build being unprepared for this:
```
2024.05.22 19:42:46 #8 4.691 go: downloading github.com/mattn/go-colorable v0.1.6
2024.05.22 19:42:46 #8 4.694 go: downloading github.com/remyoudompheng/bigfft v0.0.0-20200410134404-eec4a21b6bb0
2024.05.22 19:42:46 #8 4.741 go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
2024.05.22 19:42:46 #8 4.741 go: downloading github.com/hashicorp/go-immutable-radix v1.1.0
2024.05.22 19:42:46 #8 4.805 go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
2024.05.22 19:42:47 #8 5.671 go/vt/vtctl/reparentutil/slack_cross_cell_shim.go:3:8: reading github.com/slackhq/vitess-addons/go.mod …
```
=> `slack-15.0`: fix private repo git config in docker build

build.env, docker/base/Dockerfile.mariadb, docker/base/Dockerfile.mariadb103, docker/base/Dockerfile.mysql80, docker/base/Dockerfile.percona57, docker/base/Dockerfile.percona80
This PR refactors https://github.com/slackhq/vitess/pull/367 by moving the `git config` commands to setup private-repo access (for our custom durability policy) into `build.env`, so the logic is more general and the GitHub token is not leaked in CI output
A separate, internal PR will occur to add `GOPRIVATE` to our CI environment
=> `slack-15.0`: refactor private go dep config from #367

go/mysql/sql_error.go, go/mysql/sql_error_test.go, go/vt/throttler/max_replication_lag_module.go, go/vt/throttler/max_replication_lag_module_test.go
Backports:
1. https://github.com/vitessio/vitess/pull/12620
2. https://github.com/vitessio/vitess/pull/12949
3. https://github.com/vitessio/vitess/pull/14875
=> `slack-15.0`: backport required Transaction Throttler PRs, pt. 4

examples/local/scripts/vtgate-up.sh, go/vt/discovery/keyspace_events.go, go/vt/discovery/keyspace_events_test.go, go/vt/topo/topoproto/srvkeyspace.go
This PR replaces https://github.com/slackhq/vitess/pull/322 using `git cherry-pick` to preserve commit history
Backports:
1. https://github.com/vitessio/vitess/pull/13010
2. https://github.com/vitessio/vitess/pull/13856
=> `slack-15.0`: backport `vtgate` buffer fix vitessio/vitess#13856

go.mod, go.sum, go/test/endtoend/vtgateproxytest/failure_test.go, go/test/endtoend/vtgateproxytest/main_test.go, go/test/endtoend/vtgateproxytest/rebalance_test.go, go/test/endtoend/vtgateproxytest/scale_test.go, go/test/endtoend/vtgateproxytest/vtgateproxy_test.go, go/vt/vtgateproxy/discovery.go, go/vt/vtgateproxy/firstready_balancer.go, go/vt/vtgateproxy/vtgateproxy.go
Add end to end tests for vtgateproxy.
* A single vtgate and vtgateproxy process, in both round_robin and first_ready mode, [testing 1 unsharded write and read](https://github.com/slackhq/vitess/pull/364/files#diff-4e80b540cb67cc5a5336b0890e0a9ad67e2aeaf2a34ac82a839168743b6474e8R94)
* A test of [a single vtgate failure](https://github.com/slackhq/vitess/pull/364/files#diff-3bb3c1c33588b233837af63547618a3a5b52bf450d5c7168436ce957a0da0208R113) in a pool of connections in round_robin mode
* A test of an [active vtgate failure](https://github.com/slackhq/vitess/pull/364/files#diff-3bb3c1c33588b233837af63547618a3a5b52bf450d5c7168436ce957a0da0208R221) in first_ready mode
* A test of cluster rebalancing as vtgates are added, in both round_robin and first_ready mode
* This test is currently flappy …
=> Vtgateproxy E2E tests

go/vt/vtgate/vtgate.go, go/vt/vttablet/tabletserver/query_engine.go, go/vt/vttablet/tabletserver/query_engine_test.go, go/vt/vttablet/tabletserver/query_executor.go
Backporting [this approved-but-unmerged upstream PR](https://github.com/vitessio/vitess/pull/15897) so we can provide the output upstream requested
This provides us SQL text stats requested internally
=> `slack-15.0`: backport vitessio/vitess#15897

go/vt/vtgateproxy/discovery.go, go/vt/vtgateproxy/firstready_balancer.go
Change the discovery layer to pass in the pool type as part of the Address Attributes, and use that to maintain a map of current connections for each pool type.
=> add proper support for pool types to first_ready balancer

go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vtorc/logic/tablet_discovery.go, go/vt/vtorc/logic/tablet_discovery_test.go
Backports https://github.com/vitessio/vitess/pull/15991 from v20
- Issue: https://github.com/vitessio/vitess/issues/15990
- Fix PR: https://github.com/vitessio/vitess/pull/15991
=> `slack-15.0`: Add timeout to all the contexts used for RPC calls in vtorc (#15991)

go/vt/vtgateproxy/mysql_server.go
When a connection is closed or reset before it is properly established, the existing ::getSession will log a spurious error since the connection has no attributes to extract for the pool type.
Fix this by refactoring so that when closing a connection we only act on the session object if one already existed, i.e. the conn was used before.
=> fix spurious errors when closing inactive connections

examples/local/scripts/vtgate-up.sh, go/vt/discovery/keyspace_events.go, go/vt/discovery/keyspace_events_test.go, go/vt/topo/topoproto/srvkeyspace.go
…'re doing a reshard (#13856)
backport https://github.com/vitessio/vitess/pull/13856 (redo https://github.com/slackhq/vitess/pull/321)
v15: https://github.com/slackhq/vitess/pull/377
=> Backport 13856 - resharding error fix

go/test/endtoend/vtgateproxy/rebalance_test.go, go/test/endtoend/vtgateproxy/scale_test.go, test/config.json
* Add vtgateproxy tests to CI
* Tests will now run along with other end to end tests
* Refactor tests to make them less flappy
* Make tests deterministic instead of probabilistic
* Refactor for increased readability
=> VTGateProxy CI

go/cmd/vtbench/vtbench.go
This PR fixes a crash in v15's `vtbench`, reproduction:
```bash
tvaillancourt@tvailla-ltmxctu vitess % git checkout slack-15.0
Switched to branch 'slack-15.0'
Your branch is up to date with 'origin/slack-15.0'.
tvaillancourt@tvailla-ltmxctu vitess % make build
Thu Jul 11 18:07:08 CEST 2024: Building source tree
tvaillancourt@tvailla-ltmxctu vitess % ./bin/vtbench                                             
vtbench flag redefined: log_rotate_max_size
panic: vtbench flag redefined: log_rotate_max_size
goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc00012c000, 0xc0001317c0)
github.com/spf13/pflag@v1.0.5/flag.go:848 +0x5fc
github.com/spf13/pflag.(*FlagSet).VarPF(0xc00012c000, {0x604d378, 0x6611ab8}, {0x5a8f4e2, 0x13}, {0x0, 0x0}, {0x5ab2c9f, 0x36}) …
```
=> `slack-15.0`: fix crash in `vtbench`

docker/base/Dockerfile, docker/base/Dockerfile.mysql57, docker/base/Dockerfile.percona57, docker/base/Dockerfile.percona80
This PR copies [a fix from v15](https://github.com/slackhq/vitess/pull/367) for docker build-time problems cloning our private addons repo
=> `slack-19.0`: fix docker base build + git private repo

.github/workflows/codeql_analysis.yml, .github/workflows/upgrade_downgrade_test_backups_e2e.yml, .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml, .github/workflows/upgrade_downgrade_test_backups_manual.yml, .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries.yml, .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema.yml, .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml, .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml, test/templates/cluster_endtoend_test_mysql57.tpl, test/templates/dockerfile.tpl
**Note: no golang code is changed in this PR, it impacts CI only**
This PR fixes v15 CI that fails on installing `percona-xtrabackup-24` due to a change on Percona's mirror 
Error this fixes was `E: Unable to locate package percona-xtrabackup-24`
=> `slack-15.0`: fix broken CI due to `percona-xtrabackup-24` repo problem

go/vt/vtgateproxy/discovery.go
The goroutine that updates each resolver when the hosts file changes reads the lists of resolvers while they may be concurrently appended to if `Build` is called. Synchronize both accesses with the existing mutex in the resolver builder.
=> Access JSONGateResolverBuilder.resolvers under a lock

go/vt/vtgateproxy/discovery.go, go/vt/vtgateproxy/vtgateproxy.go
When there are a lot more targets than the number of connections in the pool, then it's possible that if the list of hosts changes, the builder might pick a totally new set of hosts than the previously selected ones, none of which will have established subconns.
Instead of giving this new list to the picker immediately, first combine it with the list of hosts that were previously selected, so that those subconns have some time to warm up while the current set is still in the list.
=> vtgateproxy: add conn warmup time

go/vt/vtgateproxy/discovery.go
Add a lock around r.currentAddrs just for extra thread safety.
=> vtgateproxy: add a lock for safety

go/flags/endtoend/vtgate.txt, go/vt/vtgate/tabletgateway.go
The tablet balancer was implemented as a local feature in https://github.com/slackhq/vitess/pull/433. The feature is now approved upstream https://github.com/vitessio/vitess/pull/16351. The functionality remains the same but the flags were renamed upstream to match convention.
=> balancer flags renamed to match upstream

go/flags/endtoend/vtgate.txt, go/vt/vtgate/balancer/balancer.go, go/vt/vtgate/balancer/balancer_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tabletgateway_test.go, go/vt/vtgate/vtgate.go, go/vt/vtorc/logic/tablet_discovery_test.go
Backport of flow based tablet balancer from [upstream PR](https://github.com/vitessio/vitess/pull/16351)
=> flow based tablet load balancer (#16351)

go/vt/wrangler/traffic_switcher.go
This is a backport of PR https://github.com/vitessio/vitess/pull/12992 which failed to get backported to v15 back in the day, so now we have to make our own patch.
=> use switcher struct when switching shard reads during a reshard event

go.mod, go.sum, go/vt/vtorc/logic/topology_recovery.go
We'd like to raise a problem for conductor to clean up the demoted primary post prs/ers.
Also send slack messages when vtorc tries to resolve a problem it detects
Depends on: https://slack-github.com/slack/vitess-bedrock/pull/563/files
=> raise orc-dead-tablet after vtorc reparent

go/vt/vtorc/logic/topology_recovery.go
Add additional logging for when a recovery is successful or failed with an error. Update when we send slack messages to avoid rate limiting.
=> log when recovery is successful/failed + fix messages

go/vt/mysqlctl/xtrabackupengine.go, go/vt/mysqlctl/xtrabackupengine_test.go
backport upstream https://github.com/vitessio/vitess/pull/16304 (v15 done in #510) 
=> v19: backport: fixing issue with xtrabackup and long gtids (#16304)

go/vt/discovery/healthcheck.go, go/vt/discovery/tablet_picker.go, go/vt/discovery/topology_watcher.go, go/vt/discovery/topology_watcher_test.go, go/vt/topo/consultopo/error.go, go/vt/topo/errors.go, go/vt/topo/etcd2topo/error.go, go/vt/topo/memorytopo/file.go, go/vt/topo/memorytopo/memorytopo.go, go/vt/topo/shard.go, go/vt/topo/tablet.go, go/vt/topo/tablet_test.go, go/vt/topo/zk2topo/error.go, go/vt/topotools/tablet.go, go/vt/topotools/utils.go, go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/grpcvtctldserver/topo.go, go/vt/wrangler/shard.go, go/vt/wrangler/split.go
This backports upstream PR https://github.com/vitessio/vitess/pull/14693, with a few minor changes to make it work with the Go
version we are using and a small change to topology_watcher.go so that test cases reflect
and test for the same behavior as the upstream code. The description of the original PR
follows:
VTGate's healthcheck module currently calls GetTablet for each tablet alias that it discovers
in a cell. Instead we can use GetTabletsForCell to fetch all tablets for a cell at once.
This PR does a few more things:
* GetTabletsForCell now handles the case where the response size violates gRPC limits by
falling back to one tablet at a time in case of error.
* Previously, the one tablet at a time method had unlimited concurrency. In this PR we
introduce a configuration option for …
=> Backport 14693 - Use GetTabletsByCell in healthcheck

go/vt/vtgate/vtgate.go
This PR re-backport the early backport of upstream PR #15897
It seems the rename of this metric was not backported down after the early backport. [Correct name on `main` here](https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/vtgate.go#L214)
=> `slack-15.0`: Add sql text counts stats to `vtcombo`,`vtgate`+`vttablet` (vitessio#15897)

go/vt/discovery/healthcheck.go, go/vt/discovery/healthcheck_test.go, go/vt/discovery/keyspace_events_test.go, go/vt/discovery/topology_watcher_test.go, go/vt/throttler/demo/throttler_demo.go, go/vt/throttler/replication_lag_cache.go, go/vt/throttler/replication_lag_cache_test.go, go/vt/throttler/throttler.go, go/vt/throttler/throttler_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go, go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
Backport v21 `txthrottler` fixes:
1. https://github.com/vitessio/vitess/pull/16899
2. https://github.com/vitessio/vitess/pull/16871
These fixes stop `txthrottler` from crashing `vttablet`
=> `slack-19.0`: backport `txthrottler` fixes from v21

go/vt/mysqlctl/xtrabackupengine.go, go/vt/mysqlctl/xtrabackupengine_test.go
backport upstream https://github.com/vitessio/vitess/pull/16304
=> backport: fixing issue with xtrabackup and long gtids (#16304)

go/flags/endtoend/vttablet.txt, go/vt/vttablet/tabletmanager/rpc_replication.go
In v19, PRS set the old primary super_read_only unconditionally during the demotion process. If we downgrade that tablet to v15, restart will fail with the error: 
```
I1014 11:21:28.334578  336986 metadata_tables.go:82] Populating _vt.local_metadata table...
F1014 11:21:28.335299  336986 tm_init.go:775] RestoreFromBackup failed: The MySQL server is running with the --super-read-only option so it cannot execute this statement (errno 1290) (sqlstate HY000) during query: CREATE DATABASE IF NOT EXISTS _vt
```
=> Disable super_read_only during PRS for v15->v19 migration

go/test/endtoend/vtgate/queries/vexplain/vexplain_test.go, go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go, go/test/endtoend/vtgate/schematracker/unsharded/st_unsharded_test.go
This PR ensures `vexplain` and known-failing-`schematracker` unit tests run on version >= v16 only. Hiding the failing `schematracker` tests is safe to do as we don't use the feature yet
The downgrade tests _(on `slack-15.0`)_ for `vexplain` currently fail because that feature doesn't exist yet
Downgrade CI _(with `slack-15.0`)_ after this PR:
And still working on non-downgrade tests:
=> `slack-19.0`: skip `vexplain`/`schematracker` tests in downgrade e2e tests

go.mod, go.sum, go/vt/vtorc/inst/analysis_dao.go, go/vt/vtorc/inst/analysis_dao_test.go, go/vt/vtorc/inst/audit_dao.go, go/vt/vtorc/inst/instance_dao.go, go/vt/vtorc/logic/vtorc.go
Backport v20 PR https://github.com/vitessio/vitess/pull/15948 to `slack-19.0` so we can observe several stats that are hidden from us _(due to being exported as `go-metrics` only)_
https://github.com/vitessio/vitess/pull/15948
=> `slack-19.0`: vtorc: Switch to Vitess stats (#15948)

go/vt/vtgate/planbuilder/operators/plan_query.go, go/vt/vtgate/planbuilder/testdata/select_cases.json
This PR backports https://github.com/vitessio/vitess/pull/17085 to `slack-19.0`. This is a v19 backport of PR https://github.com/vitessio/vitess/pull/17077 _(from v22)_
https://github.com/vitessio/vitess/pull/17077
=> `slack-19.0`: backport v19 backport of vitessio/vitess PR #17077

go/vt/external/golib/sqlutils/sqlite_dialect.go, go/vt/external/golib/sqlutils/sqlite_dialect_test.go
This PR improves the insert efficiency of a func used by `vtorc` during DML queries. This func is being seen as the top consumer of CPU in profiles
Before benchmark:
```bash
BenchmarkToSqlite3Dialect_Insert-16    	     758	   1695979 ns/op
```
After benchmark:
```bash
BenchmarkToSqlite3Dialect_Insert-16    	     723	   1517499 ns/op
```
This is about a 10.5% improvement for `insert`/`replace` queries, which should be the most frequent
=> `slack-19.0`: optimize `sqlutils.ToSqlite3Dialect`

go/vt/external/golib/sqlutils/sqlite_dialect.go, go/vt/external/golib/sqlutils/sqlite_dialect_test.go, go/vt/vtorc/db/db.go
As a follow-up to upstreaming https://github.com/slackhq/vitess/pull/545, I made a few more improvements to the optimisation. Now read queries bypass several regex filters and benchmark 19% better
See https://github.com/vitessio/vitess/pull/17113 for a full explanation. This is a pre-backport of that PR, on top of the original POC
```bash
goos: darwin
goarch: amd64
pkg: vitess.io/vitess/go/vt/external/golib/sqlutils
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkToSqlite3Dialect_Insert1000
BenchmarkToSqlite3Dialect_Insert1000-16    	       1	1870643229 ns/op
BenchmarkToSqlite3Dialect_Select
BenchmarkToSqlite3Dialect_Select-16        	    3541	    330667 ns/op
PASS
ok  	vitess.io/vitess/go/vt/external/golib/sqlutils	4.660s
```
```bash
goos: darwin
goarch: amd64
pkg: …
```
=> `slack-19.0`: optimize `sqlutils.ToSqlite3Dialect`, part 2

go/flags/endtoend/vttablet.txt, go/vt/discovery/healthcheck.go
This PR adds important flags for tuning topo/discovery behaviour in `vttablet`, which will benefit `txthrottler`
With this PR I suggest we:
1. Set `--topo_read_concurrency` to `4`, equal to cells _(from `32` 😬)_
- Some functions start a worker per cell, so >= 4 is a good idea
3. Increase `--tablet_refresh_interval duration` _(currently `1m`)_
4. Enable `--tablet_refresh_known_tablets` to cache records
5. Set `--healthcheck-dial-concurrency` to `4`-`8`-ish
cc @ejortegau 
=> `slack-15.0`: add topo/healthcheck flags to `vttablet` for `txthrottler`

go/vt/discovery/keyspace_events.go, go/vt/discovery/keyspace_events_test.go, go/vt/srvtopo/discover.go, go/vt/srvtopo/discover_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vtgate/tabletgateway_flaky_test.go, go/vt/vtgate/tabletgateway_test.go
backport https://github.com/vitessio/vitess/pull/16655 
=> backport upstream 16655 - Fix race condition that prevents queries from being buffered after vtgate startup

go.mod, go.sum, go/vt/vtorc/logic/topology_recovery.go
This PR updates `slackhq/vitess-addons` to `v0.19.4` to remove support for proxying http requests
=> `slack-19.0`: update to `slackhq/vitess-addons@v0.19.4`

go/vt/discovery/healthcheck.go, go/vt/discovery/tablet_health_check.go
Add more logging around tablet health stats update and broadcast
=> Add debugging logs for stale shard health stats on vtgates

go/vt/vtgateproxy/discovery.go, go/vt/vtgateproxy/firstready_balancer.go, go/vt/vtgateproxy/mysql_server.go, go/vt/vtgateproxy/sim/vtgateproxysim.go, go/vt/vtgateproxy/sticky_random_balancer.go, go/vt/vtgateproxy/vtgateproxy.go
Implement a couple improvements to the vtgateproxy to support:
* New sticky_random load balancer which implements round robin over connections while maintaining the mapping from a given webapp mysql connection to a given downstream GRPC.
* Add support to discovery of a new `--num_backup_connections` option to include of vtgates in _remote_ zones
* Respect the zone locality in the picker so that we bias towards local connections if available and only fall back if needed.
Verified in dev by forcing a webapp host to use a hand-built proxy running on localhost
Running the client and looking at /channelz/ shows that sticky_random only uses the local conns when they're available.
Also verified that it's now picking one backup conn by including that in the debug output:
=> vtgateproxy: sticky random balancer and remote zone backup connections

go/test/endtoend/vtgateproxy/failure_test.go, go/test/endtoend/vtgateproxy/rebalance_test.go, go/test/endtoend/vtgateproxy/scale_test.go, go/test/endtoend/vtgateproxy/vtgateproxy_test.go, go/vt/vtgateproxy/discovery.go, go/vt/vtgateproxy/firstready_balancer.go, go/vt/vtgateproxy/mysql_server.go, go/vt/vtgateproxy/sim/vtgateproxysim.go, go/vt/vtgateproxy/sticky_random_balancer.go, go/vt/vtgateproxy/vtgateproxy.go
#593 onto vtgateproxy v19
add test coverage
=> vtgateproxy: sticky random balancer and remote zone backup connections v19

go/vt/topo/faketopo/faketopo.go, go/vt/vtorc/logic/tablet_discovery.go, go/vt/vtorc/logic/tablet_discovery_test.go
This PR is an early backport of v22 bugfix PR: https://github.com/vitessio/vitess/pull/17718
=> `slack-19.0`: `vtorc`: improve handling of partial cell topo results

go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go, go/test/endtoend/vtgate/queries/derived/derived_test.go, go/test/endtoend/vtgate/queries/foundrows/found_rows_test.go
This PR addresses several query serving CI failures when upgrade/downgrade testing with `slack-15.0` VTGates that don't have certain functionality
For context: v18 was used as the previous version because upstream's `release-19.0` branch successfully downgrades with v18
Example failures below:
```
2025-02-10T15:04:33.0364151Z === RUN   TestGroupBy
2025-02-10T15:05:33.1593242Z     aggregation_test.go:119: 
2025-02-10T15:05:33.1595331Z         	Error Trace:	/home/runner/work/vitess/vitess/go/test/endtoend/utils/cmp.go:201
2025-02-10T15:05:33.1596608Z         	            				/home/runner/work/vitess/vitess/go/test/endtoend/utils/cmp.go:65
2025-02-10T15:05:33.1598036Z         	            				/home/runner/work/vitess/vitess/go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go:119 …
```
=> `slack-19.0`: skip tests that will fail on v15 downgrade testing

go/vt/vtorc/inst/shard_dao.go, go/vt/vtorc/inst/shard_dao_test.go, go/vt/vtorc/logic/keyspace_shard_discovery.go
This PR pre-backports v22 PR https://github.com/vitessio/vitess/pull/17815 to `slack-19.0`
TL;DR: this adds stats for what shards VTOrc is watching
=> `slack-19.0`: Add stats for shards watched by VTOrc

go/pools/smartconnpool/pool.go, go/pools/smartconnpool/pool_test.go
backport https://github.com/vitessio/vitess/pull/17818
=> backport 17818: pool: reopen connection closed by idle timeout (#17818)

go/vt/vtorc/inst/shard_dao_test.go, go/vt/vtorc/logic/keyspace_shard_discovery.go, go/vt/vtorc/logic/keyspace_shard_discovery_test.go
This PR backports the finalized version of v22 PR: https://github.com/vitessio/vitess/pull/17815
We already pre-backported this, but there were more fixes/tweaks after that occurred. This backports what was merged into v22
=> `slack-19.0`: backport finalized version of v22 PR vitessio/vitess#17815

go/vt/vtorc/inst/shard_dao.go, go/vt/vtorc/inst/shard_dao_test.go, go/vt/vtorc/inst/tablet_dao.go, go/vt/vtorc/inst/tablet_dao_test.go, go/vt/vtorc/logic/keyspace_shard_discovery.go, go/vt/vtorc/logic/tablet_discovery.go
This PR backports more tweaks from v22 PR https://github.com/vitessio/vitess/pull/17911 based on testing. It is still unmerged
TL;DR: tablets-by-cell and tablets-by-shard counts are added, replacing the `ShardsWatch` metric
=> `slack-19.0`: re-backport tweaks from vitessio/vitess#17911

go/ioutil/writer.go, go/vt/mysqlctl/fakemysqldaemon.go, go/vt/mysqlctl/mysqlshellbackupengine.go, go/vt/mysqlctl/mysqlshellbackupengine_test.go
This backports a required fix when using the `mysqlshell` backup engine. 
See the upstream PR: https://github.com/vitessio/vitess/pull/17000/
=> fix releasing the global read lock when mysqlshell backup fails (#17000)

go/flags/endtoend/vtorc.txt, go/vt/vtorc/config/config.go, go/vt/vtorc/db/generate_base.go, go/vt/vtorc/discovery/queue.go, go/vt/vtorc/discovery/queue_test.go, go/vt/vtorc/inst/instance_dao.go, go/vt/vtorc/inst/shard_dao.go, go/vt/vtorc/inst/shard_dao_test.go, go/vt/vtorc/inst/tablet_dao.go, go/vt/vtorc/inst/tablet_dao_test.go, go/vt/vtorc/logic/keyspace_shard_discovery.go, go/vt/vtorc/logic/keyspace_shard_discovery_test.go, go/vt/vtorc/logic/tablet_discovery.go, go/vt/vtorc/logic/topology_recovery.go, go/vt/vtorc/logic/vtorc.go
This PR backports more v22 VTOrc fixes we run on `slack-19.0`:
1. https://github.com/vitessio/vitess/pull/17834
2. https://github.com/vitessio/vitess/pull/17866
3. https://github.com/vitessio/vitess/pull/17815
4. https://github.com/vitessio/vitess/pull/17515
5. https://github.com/vitessio/vitess/pull/17825
6. https://github.com/vitessio/vitess/pull/17857
7. https://github.com/vitessio/vitess/pull/17900
8. https://github.com/vitessio/vitess/pull/17911
9. https://github.com/vitessio/vitess/pull/17937
-   [x] Did the new or modified …
=> `slack 21.0`: backport v22 VTOrc improvements, part 2

go/cmd/vtgateproxy/vtgateproxy.go, go/vt/vtgateproxy/sim/go.mod, go/vt/vtgateproxy/sim/go.sum
a couple of minor things
- add a `go.mod` to `go/vt/vtgateproxy/sim` - missing deps breaking the main build
- rewire channelz endpoint - servenv stopped using the default servemux which inadvertently broke our channelz setup
this branch is currently deployed to loadtest dev and working fine
=> vtgateproxy v19 fixes

go/vt/vtorc/logic/tablet_discovery.go, go/vt/vtorc/logic/topology_recovery.go, go/vt/vtorc/logic/vtorc.go, go/vt/vtorc/logic/vtorc_test.go
This PR backports additional `vtorc` stats from https://github.com/vitessio/vitess/pull/17977
https://github.com/vitessio/vitess/pull/17977
-   [x] Did the new or modified tests pass consistently locally and on CI?
=> `slack-19.0`: backport additional `vtorc` stats from vitessio/vitess#17977

go/vt/topo/consultopo/server.go, go/vt/topo/consultopo/server_flaky_test.go
This PR is an early backport of v23 PR: https://github.com/vitessio/vitess/pull/18152
This PR checks that consul static credentials were actually loaded, to address a problem we saw when the consul token is valid but empty, eg: `{}`
-   [x] Did the new or modified tests pass consistently locally and on CI?
=> `slack 19.0`: pre backport vitessio/vitess#18152

go.mod, go.sum
This PR resolves a security vuln in `slack-19.0` by upgrading `github.com/golang/glog` to `v1.2.4`
=> `slack-19.0`: update `github.com/golang/glog` to `v1.2.4`

go.mod, go.sum, go/vt/vtorc/logic/topology_recovery.go
Update `slack-19.0` to https://github.com/slackhq/vitess-addons/releases/tag/v0.19.9
=> `slack-19.0`: use `slackhq/vitess-addons@v0.19.9`

go/vt/topo/consultopo/server.go, go/vt/topo/consultopo/server_flaky_test.go, go/vt/vtorc/logic/tablet_discovery.go, go/vt/vtorc/logic/topology_recovery.go, go/vt/vtorc/logic/vtorc.go, go/vt/vtorc/logic/vtorc_test.go
This backports more v22/v23 optimizations we rely on for VTOrc:
1. https://github.com/vitessio/vitess/pull/17977
2. https://github.com/vitessio/vitess/pull/18152 _(pre-backport - 50% approved upstream)_
-   [x] Did the new or modified tests pass consistently locally and on CI?
=> `slack 21.0`: backport v22/v23 VTOrc improvements, part 3

go/flags/endtoend/vtcombo.txt, go/flags/endtoend/vttablet.txt, go/sync2/consolidator.go, go/sync2/consolidator_test.go, go/sync2/fake_consolidator.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/tabletenv/config.go
This PR backports v22 PR https://github.com/vitessio/vitess/pull/17244 to `slack-21.0`, as we will soon rely on this feature
-   [x] Did the new or modified tests pass consistently locally and on CI?
=> `slack-21.0`: backport vitessio/vitess#17244

examples/backups/restart_tablets.sh, go/test/endtoend/reparent/plannedreparent/reparent_test.go, go/vt/vtctl/grpcvtctldserver/server_slow_test.go, go/vt/vtctl/grpcvtctldserver/server_test.go, go/vt/vtctl/grpcvtctldserver/testutil/test_tmclient.go, go/vt/vtctl/reparentutil/planned_reparenter.go, go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go, go/vt/vtctl/reparentutil/util.go
Revert `Improvements to PRS #13623`
=> Revert upstream 13623: remove the call of verifyAllTabletsReachable in PRS

docker/bootstrap/Dockerfile.common, docker/bootstrap/build.sh
allows `make docker_bootstrap` to work with GH token for slack-19.0
-   [ NA] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ NA] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ NA ] Tests were added or are not required
-   [ NA ] Did the new or modified tests pass consistently locally and on CI?
-   [ NA ] Documentation was added or is not required
utility for building, not deployment related
=> fix `make docker_bootstrap` to be compatible with vitess-addons

examples/region_sharding/101_initial_cluster.sh, go/test/endtoend/vtgate/schematracker/loadkeyspace/schema_load_keyspace_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vtgate/vtgate.go
This reverts commit 24c3c26d2956c8449702e4168806f985a29e5393.
vtgate startup hung due to infinite wait of tablet healthchecks
revert https://github.com/slackhq/vitess/pull/644
=> Revert "Improve tablet types to wait (#643)"

go/flags/endtoend/vtorc.txt, go/test/endtoend/vtorc/readtopologyinstance/main_test.go, go/vt/vtorc/config/config.go, go/vt/vtorc/logic/vtorc.go
A `slack-19.0` backport of v23 PR https://github.com/vitessio/vitess/pull/18005
=> `slack-19.0`: allow vtorc recoveries to be disabled from startup (#18005)

go/flags/endtoend/vtcombo.txt, go/flags/endtoend/vtgate.txt, go/flags/endtoend/vttablet.txt, go/streamlog/streamlog.go, go/streamlog/streamlog_test.go, go/vt/vtgate/logstats/logstats.go, go/vt/vtgate/logstats/logstats_test.go, go/vt/vttablet/tabletserver/tabletenv/logstats.go
Backport the following PR from Vitess/main:
```
commit b9fcdba600f4cc09e7fa920fb4815cc22cf3c751
Author: Henry Haiying Cai <HenryCaiHaiying@users.noreply.github.com>
Date:   Wed Jul 30 00:05:39 2025 -0700
Add support for querylog-time-threshold duration flag for query logging (#18520)
Signed-off-by: Henry Cai <henry.cai@slack-corp.com>
```
=> Add support for querylog-time-threshold duration flag for query logging ((#18520)
